services:
  #  website:
  #    image: nginx
  #    depends_on:
  #      database:
  #        condition: service_healthy # service healthy always points to healthcheck -> test

  database:
    image: mysql
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: sampledb
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    ports:
      - 3306:3306
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 5
    restart: always
    volumes:
      - mysql_data:/var/lib/mysql
      - ./schema.sql:/docker-entrypoint-initdb.d/1.sql
      - ./data.sql:/docker-entrypoint-initdb.d/2.sql # in mysql initial sql files are read the order of the name

volumes:
  mysql_data:
