
services:
  redisinsight:
    image: redis/redisinsight:latest
    container_name: redisinsight
    ports:
      - "5540:5540"
    volumes:
      - redisinsight:/data
    restart: always
    extra_hosts:
      - "host.docker.internal:host-gateway"

volumes:
  redisinsight:
    driver: local